### ISSUE TITLE
defaultSearchEngine dosent work

### ISSUE THREAD

**Issue by laycookie** [schizofox/schizofox#102]
Sorry if I just misunderstood how it works but the README makes me think that just adding `defaultSearchEngine = "Brave"` should make Brave my default search engine, but instead my search engine keeps on being DuckDuckGo.

**Comment by NotAShelf** [comment]
@sioodmy I don't use brave, could you take a look? Perhaps the policies have changed.

**Comment by sioodmy** [comment]
try to remove `~/.mozilla` directory (and back it up of course) and tell us if the issue persist

**Comment by laycookie** [comment]
@sioodmy  Yes the issue doesn't go away.

**Comment by SkettiSouls** [comment]
You need to add a search engine named `Brave` using `search.addEngines`, otherwise firefox doesn't know what search engine you're telling it to use.
