### ISSUE TITLE
Fix 30 frames per second lock

### ISSUE THREAD

**Issue by laycookie** [schizofox/schizofox#103]
Hello, not sure how it is on other Wayland compositors, I personally use Hyperland and on it the frame-rate is locked at 30 fps by default, I also heard that other compositors also have a frame rate locks usually at around 60 fps so I'm wondering if we should perhaps set layout.frame_rate to 120 by default for the experience to at least be consistent.

**Comment by NotAShelf** [comment]
Citing vaxry on Hyprland's frame rate:

> apps can render at whatever fps they want
> hyprland will render (or try) at your displays hz

Therefore the limitation doesn't sound like something we should try and account for. I also don't want to make assumptions about other people's display setups by default, so I'd like to leave it as is. You can set `layout.frame_rate` yourself in `programs.schizofox.settings`.

**Comment by laycookie** [comment]
@NotAShelf I can understand not wanting to make an assumption about someones hardware, so I don't mind leaving it as is. However I think we should at least add `layout.frame_rate` set to 60 in the example config in the README because having to figure out why your browser is running in 30fps by default is a bit annoying.

Update on the issue:
I found the culprit, apparently setting `security.sandbox = true` is what results in the frame drop. Importantly, however, I don't notice the frame rate drop on my second 144Hz display; it only becomes noticeable when I drag the window to my first screen that runs at 60Hz.

**Comment by NotAShelf** [comment]
That appears like a Hyprland issue somehow, but I don't see how nixpak would be breaking Hyprland's framerate detection. I'll investigate this week, as I should *finally* have some free time to work on Schizofox again.

**Comment by laycookie** [comment]
It appears that if you disable `security.sandbox` you will need to wipe Mozilla dotfiles for this bug to go away. Not perfect but for now the project probably shouldn't focus on this issue so I will be closing it.
