### ISSUE TITLE
Update to firefox-esr-128-unwrapped

### ISSUE THREAD

**Issue by surfaceflinger** [schizofox/schizofox#115]
Been using ESR 128 with Schizofox for few days, everything seems fine.

The new "Privacy-Preserving Attribution" thingie can be disabled with `dom.private-attribution.submission.enabled`

Anything else that changed between 115 and 128?

**Comment by NotAShelf** [comment]
There isn't a concrete reason we're lagging behind in ESR version - other than that I have not had the time to go through the changelogs.

I've noticed that recent versions of Firefox have been becoming more "corporate", so to speak, and I'd like to go through whatever changelogs and policy templates are available before I update the default package.
