### ISSUE TITLE
Reddit does not log  in with google

### ISSUE THREAD

**Issue by guy925** [schizofox/schizofox#121]
The page where it logs in is just blank. It does go through the sign in process, but hangs on [this website.
](https://accounts.google.com/gsi/transform)
![20241023_07h14m34s_grim](https://github.com/user-attachments/assets/2d95abfd-e5a1-4ad8-a240-b28c748fe0b4)

**Comment by NotAShelf** [comment]
I consider this a feature - logging with with google is a massive privacy issue.

**Comment by guy925** [comment]
> I consider this a feature - logging with with google is a massive privacy issue.

ok ill try to make my reddit account work not only with google

**Comment by guy925** [comment]
ok fixed
