### ISSUE TITLE
Home-Manager conflict with vanilla Firefox

### ISSUE THREAD

**Issue by veri-tty** [schizofox/schizofox#123]
I am not sure if this is reproducible for others, but both Schizofox and Firefox home manager configurations attempt to edit and work with ~/.mozilla/firefox/profiles.ini
This creates the following error when rebuilding:

`
error:
       Failed assertions:
       - ml profile: Conflicting managed target files: .mozilla/firefox/profiles.ini
         This may happen, for example, if you have a configuration similar to
           home.file = {
             conflict1 = { source = ./foo.nix; target = "baz"; };
             conflict2 = { source = ./bar.nix; target = "baz"; };
           }
`

**Comment by NotAShelf** [comment]
This is to be expected, you should only enable one of them.

**Comment by veri-tty** [comment]
ahh, okay thank you :)
