### ISSUE TITLE
pointer issue

### ISSUE THREAD

**Issue by sioodmy** [schizofox/schizofox#24]
![image](https://github.com/schizofox/schizofox/assets/81568712/41277365-e0c3-4d48-88ef-d877a7f58524)
`let cursor = config.home.pointerCursor.package or pkgs.someCursorPackage`

**Comment by sioodmy** [comment]
![image](https://github.com/schizofox/schizofox/assets/81568712/41277365-e0c3-4d48-88ef-d877a7f58524)
`let cursor = config.home.pointerCursor.package or pkgs.someCursorPackage`

**Comment by sioodmy** [comment]
not sure if overwriting default cursor is expected behavior tho

**Comment by NotAShelf** [comment]
`or` does not override
it'll fall back to our given cursor theme if config.home.pointerCursor is not defined
