### ISSUE TITLE
Provide option to override extensions installed by default / remove extensions

### ISSUE THREAD

**Issue by alnmy** [schizofox/schizofox#26]
Currently the option defaultExtensions is [readonly](https://github.com/schizofox/schizofox/blob/main/modules/hm/default.nix#L220) so it is not as user-friendly to override the extensions installed by default, if say a user simply wants to remove one extension.

**Comment by NotAShelf** [comment]
I've kept it as readonly to not mess with the previous approach. I intend to provide an empty attrset as the default and then move our "default" addons to extraExtensions which the user can manipulate on their own accord.
