### ISSUE TITLE
Downloading / Uploading files (xdg-portal) doesn't work on first startup

### ISSUE THREAD

**Issue by alnmy** [schizofox/schizofox#31]
No errors seemingly come up for me. I'm willing to try get more information if this can't be reproduced.

**Comment by NotAShelf** [comment]
Could you provide more details on your setup? I cannot exactly reproduce this on my system, so I'd appreciate if you could share the following
- Distro
- Nix/Home-manager version
- display server (xorg? wayland?)
- are you using nixpak?
- your module config

I've heard reports of schizofox misbehaving on xorg, so more details could help resolve it.

**Comment by alnmy** [comment]
NixOS

__Versions from flake.lock__
schizofox: "rev": "dacd1e479991cb0365a2ac4429308f3dc0f6d996"
nixpkgs: "rev": "ca3c9ac9f4cdd4bea19f592b32bb59b74ab7d783", stable 23.05
home-manager:  "rev": "32d3e39c491e2f91152c84f8ad8b003420eab0a1", stable 23.05
I should note that I am using home-manager standalone

I am using Wayland with Sway. I am starting sway simply by typing in `sway` from the command-line. My Sway/Wayland configuration is more non-conventional as I don't install Sway system-wide but only in the user and just set a few general wayland settings in the wayland configuration. Below attached are some relevant configs:
<details>
  <summary>Wayland + XDG portal system</summary>
{ pkgs, config, lib, ... }:
with lib;

let
  cfg = config.admin.wayland;
in {
  options.admin.wayland = {
    enable = mkOption {
      description = "Whether to enable system configuration required to run Wayland";
      type = types.bool;
      default = false;
    };
  };

  config = mkIf (cfg.enable) {
    environment.systemPackages = with pkgs; [
      libva-utils
      vdpauinfo
      glxinfo
    ];

    hardware.opengl = {
      enable = true;
      driSupport = true;
      driSupport32Bit = true;
    };

    security.polkit.enable = true;

    xdg.portal.enable = true;
    xdg.portal.wlr.enable = true;
    xdg.portal.extraPortals = with pkgs; [ 
      xdg-desktop-portal-gtk
    ];
  };
}
</details>
<details>
  <summary>Sway home-manager with irrelevant config removed</summary>
  wayland.windowManager.sway.enable = true; 
</details>

<details>
  <summary>Schizofox configuration</summary>
{ pkgs, config, lib, inputs, ... }:
with lib;

let
  cfg = config.admin.apps.firefox;
  default = if config.admin.apps.default.browser == "firefox" then true else false;
in {
  options.admin.apps.firefox = {
    enable = mkOption {
      description = "Enable Firefox, sandboxed using Nixpak";
      type = types.bool;
      default = false;
    };
  };

  config = mkIf (cfg.enable || default) {
    programs.schizofox = {
      enable = true;
      security = {
        sanitizeOnShutdown = false;
        sandbox = true;
      };
      theme = {
        darkreader.enable = false;
        simplefox.enable = true;
      };
      extensions = {
        extraExtensions = {
          "{446900e4-71c2-419f-a6a7-df9c091e268b}".install_url = "https://addons.mozilla.org/firefox/downloads/latest/bitwarden-password-manager/latest.xpi";
        };
      };
    };   
  };
}
</details>  

Yes, I am using nixpak

Will attempt to get some logs in a bit from different services, if any appear

**Comment by alnmy** [comment]
It seems to only happen on first start of Schizofox after system startup, perhaps it's due to some required DBus service not being started at the time? Could possibly just be a fault of my configuration then. Output from `dbus-monitor` definitely shows some errors, though it's 17430 lines (<3 dbus) so I'm not risking sending the whole thing but here's some relevant lines 
```method return time=1693687281.765930 sender=:1.9 -> destination=:1.8 serial=149 reply_serial=46
   object path "/org/freedesktop/portal/desktop/request/1_8/gtk1104811804"
method call time=1693687281.802854 sender=:1.12 -> destination=org.freedesktop.DBus serial=72 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',path='/org/freedesktop/DBus',arg0='org.freedesktop.portal.Documents'"
method return time=1693687281.802912 sender=org.freedesktop.DBus -> destination=:1.12 serial=4294967295 reply_serial=72
method call time=1693687281.802926 sender=:1.12 -> destination=org.freedesktop.DBus serial=73 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.freedesktop.portal.Documents"
method return time=1693687281.802951 sender=org.freedesktop.DBus -> destination=:1.12 serial=4294967295 reply_serial=73
   string ":1.10"
method call time=1693687281.931763 sender=:1.12 -> destination=org.freedesktop.DBus serial=74 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',interface='ca.desrt.dconf.Writer',path='/ca/desrt/dconf/Writer/user',arg0path='/org/gtk/settings/file-chooser/'"
method return time=1693687281.931832 sender=org.freedesktop.DBus -> destination=:1.12 serial=4294967295 reply_serial=74
method call time=1693687282.011921 sender=:1.12 -> destination=org.freedesktop.DBus serial=75 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=StartServiceByName
   string "org.gtk.Settings"
   uint32 0
error time=1693687282.011999 sender=org.freedesktop.DBus -> destination=:1.12 error_name=org.freedesktop.DBus.Error.ServiceUnknown reply_serial=75
   string "The name is not activatable"
method call time=1693687282.017442 sender=:1.12 -> destination=org.freedesktop.DBus serial=76 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.gtk.Settings"
error time=1693687282.017525 sender=org.freedesktop.DBus -> destination=:1.12 error_name=org.freedesktop.DBus.Error.NameHasNoOwner reply_serial=76
   string "The name does not have an owner"
method return time=1693687282.962076 sender=:1.12 -> destination=:1.9 serial=77 reply_serial=148
   uint32 0
   array [
      dict entry(
         string "current_filter"
         variant             struct {
               string "All Files"
               array [
                  struct {
                     uint32 0
                     string "*"
                  }
               ]
            }
      )
      dict entry(
         string "uris"
         variant             array [
               string "file:///home/admin/media/pictures/20230831_13h40m10s_grim.png"
            ]
      )
      dict entry(
         string "writable"
         variant             boolean true
      )
      dict entry(
         string "choices"
         variant             array [
            ]
      )
   ]```

**Comment by alnmy** [comment]
I have just remembered that on my system, I use 
`services.dbus.implementation = "broker";`
so it may be a fault of dbus-broker. Will report back on this later after switching it back to the default.

**Comment by alnmy** [comment]
Closing issue as this seems to be coming from an issue with my system, as I am experiencing the same issue as this person here https://github.com/NixOS/nixpkgs/issues/17943#issuecomment-1678845592
