### ISSUE TITLE
Feature Request: Branding

### ISSUE THREAD

**Issue by mrtnvgr** [schizofox/schizofox#59]
Proposal: replace firefox logo with schizofox logo

**Comment by sioodmy** [comment]
hopefully that wont require patching ff source code. im not sure if thats possible with just userContent.css

**Comment by NotAShelf** [comment]
I've been looking into this. It seems like we **are not able to** change branding information without patching Firefox, which I think is beyond the scope of this project at the moment - especially given that we allow the user to change the package.

**Comment by jh-devv** [comment]
#99

**Comment by NotAShelf** [comment]
Closing this issue as patching Firefox is (currently) out of scope. We may revisit this in the future.
