### ISSUE TITLE
Feature request: option to include additional user preferences

### ISSUE THREAD

**Issue by xusiai** [schizofox/schizofox#75]
I would appreciate an option for additional user preferences e.g. 

```
extraConfig = ''
    user_pref("browser.tabs.firefox-view", false);
    user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
    user_pref("toolkit.coverage.opt-out", true);
''
```
Would this be feasible?

**Comment by NotAShelf** [comment]
Could [this](https://github.com/schizofox/schizofox/blob/main/modules/hm/options/general.nix#L15) be what you're looking for?

**Comment by xusiai** [comment]
> Could [this](https://github.com/schizofox/schizofox/blob/main/modules/hm/options/general.nix#L15) be what you're looking for?

Yeah I'm blind. Thanks!
