### ISSUE TITLE
Download Issues

### ISSUE THREAD

**Issue by W-Y-R** [schizofox/schizofox#88]
I'm encountering an unusual issue where downloads won't start in schizofox, despite working in other browsers. 

I've made sure that the downloads folder is correctly set in the browser, yet the issue persists.

**Comment by NotAShelf** [comment]
I've been looking into this for a few days, no idea why it occurs. Can you see it persists after disabling sandboxing?

**Comment by W-Y-R** [comment]
I can download files normally with sandboxing disabled. With it enabled, however, I receive the following error:
```
[Parent 2, Main Thread] WARNING: getpwuid_r(): failed due to unknown user id (1000): 'glib warning', file /build/firefox-115.8.0/toolkit/xre/nsSigHandlers.cpp:167

(firefox:2): GLib-WARNING **: getpwuid_r(): failed due to unknown user id (1000)
```
I'm considering this issue closed since it solved my initial issue. Of course, you are free to reopen it if you deem it necessary.
