### ISSUE TITLE
Feature request: option to disable css customization not specified in extraUserChrome and extraUserContent

### ISSUE THREAD

**Issue by xusiai** [schizofox/schizofox#92]
I would appreciate an option to disable userChrome/userContent code not explicitly specified in extraUserChrome and extraUserContent as the css Schizofox implement seem to override these options and break custom themes.

**Comment by NotAShelf** [comment]
Sounds reasonable. I'll add `defaultUserContent` `defaultUserChrome` as overridable options under `programs.schizofox.theme` once I'm on my desktop.

**Comment by xusiai** [comment]
> Sounds reasonable. I'll add `defaultUserContent` `defaultUserChrome` as overridable options under `programs.schizofox.theme` once I'm on my desktop.

Thank you.

**Comment by NotAShelf** [comment]
I've added `defaultUserChrome.enable` and `defaultUserContent.enable` in #94, which should resolve this issue. 

Feel free to open it if you find the solution unsatisfactory.
