### ISSUE TITLE
New branding

### ISSUE THREAD

**Issue by jh-devv** [schizofox/schizofox#99]
Hey, so...

The currently used logo seems a bit, weird (like... non professional, that green just really pops out)? I don't know if it's just me, but what about if we used `nix` colors since this is an `nix` based project?

I can work on this but yea! :3

**Comment by NotAShelf** [comment]
I'm not sure if we really want to with Nix colors. The glowing green color (and the resulting eye-strain) was intended as a not-so-subtle reference to "glowing" - which means you have a *very* noticeable presence on the internet. 

CC @sioodmy on this.

**Comment by jh-devv** [comment]
Yea, that makes sense, but I think it's maybe a little bit too much ;)

**Comment by sioodmy** [comment]
Thanks for the feedback, but we are not making  *just* a nix framework for firefox customization. Schizofox is not professional, because it was never meant to be. We will see in the future as the project grows.

**Comment by jh-devv** [comment]
> Thanks for the feedback, but we are not making _just_ a nix framework for firefox customization. Schizofox is not professional, because it was never meant to be. We will see in the future as the project grows.

Yea, true
